config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :artworks, only: [:index, :show] do
    resources :bookings, only: [:create]
    resources :reviews, only: [:create]
  end
  resources :bookings, only: [:index, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/artwork.rb
class Artwork < ApplicationRecord
  belongs_to :user
  has_many :images
  has_many :reviews

  validates :title, presence: true, uniqueness: { scope: :creator }

  validates :description, presence: true
  validates :description, length: { minimum: 20 }

  validates :price_per_day, presence: true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :artwork
  validates :start_date, presence: true
  validates :end_date, presence: true, comparison: { greater_than: :start_date }
  validates :duration, presence: true
  validates :total_price, presence: true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :artwork

  validates :url, presence: true
  validates :url, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :artwork
  belongs_to :user

  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }, inclusion: { in: [0, 1, 2, 3, 4, 5], message: "Please enter a rate between 0 and 5" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
  has_many :artworks
  has_many :reviews

  validates :first_name, presence: true
  validates :first_name, length: { minimum: 2 }
  validates :last_name, presence: true
  validates :last_name, length: { minimum: 2 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit::Authorization

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/artworks_controller.rb
MEDIUMS = ["All", "Painting", "Print", "Drawing", "Sculpture"]

class ArtworksController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  
  def index
    @artworks = policy_scope(Artwork)
    if params[:query].present?
      sql_query = "title ILIKE :query OR creator ILIKE :query"
      @artworks = Artwork.where(sql_query, query: "%#{params[:query]}%")
      category = params.require("category").permit(:name)
      if category[:name] != "All"
        @artworks = @artworks.where(medium: category[:name])
      end
    else
      @artworks = @artworks[0...50]
    end

    @categories = MEDIUMS
  end

  def show
    @artwork = Artwork.find(params[:id])
    authorize @artwork
    @booking = Booking.new
    @reviews = @artwork.reviews
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @booking_params = booking_params
    @booking = Booking.new(@booking_params)
    @booking.user = current_user
    @booking.artwork = Artwork.find(params[:artwork_id])
    @booking.duration = @booking.end_date - @booking.start_date
    @booking.total_price = @booking.artwork.price_per_day * (@booking.duration)
    authorize @booking
    if @booking.save
      redirect_to :bookings
    else
      render @booking.artwork, status: :unprocessable_entity
    end
  end

  def index
    @today = Date.today
    @user = current_user
    # @user_bookings = @user.bookings
    @user_bookings = policy_scope(Booking)
    @user_future_bookings = @user_bookings.select do |booking|
      booking.start_date >= @today
    end
    @user_past_bookings = @user_bookings.select do |booking|
      booking.start_date < @today
    end
    # @user_bookings = policy_scope(Booking)
    @review = Review.new
    # authorize @review

  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def booking_params
    return params.require("booking").permit(:start_date, :end_date)
   end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    authorize @review
    @artwork = Artwork.find(params[:artwork_id])
    @review.artwork = @artwork
    @review.user = current_user
    @review.save
    redirect_to artwork_path(@artwork)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artworks/_artwork.html.erb
<div class="card m-2 p-0" style="width: 26rem;">
  <a href=<%= "/artworks/#{artwork.id}" %>>
    <div class="card-artwork">
        <% image_url = artwork.images.first.url %>
        <img src=<%= image_url %> class="card-img-top" alt="...">
    </div>
  </a>
  <div class="card-body">
    <span class="card-price-day"><%= artwork.price_per_day.to_i %> $/day</span>
    <h5 class="card-title"><%= artwork.title %></h5>
    <p class="card-text"><%= artwork.creator %></p>
  </div>
</div>

app/views/artworks/index.html.erb
<%= render "shared/navbar" %>
<div class="container justify-content-center">
  <div class= "search-bar">
    <div class="col-6">
      <%= form_with url: artworks_path, method: :get, class: "d-flex mt-4" do %>
        <%= select "category", "name", @categories, class: "form-control btn-category" %>
        <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Enter a key word ..."
        %>
        <%= submit_tag "Search", class: "btn btn-search" %>
      <% end %>
      <div class="d-flex">
        <% @categories.each do |category| %>
        <% end %>
      </div>
    </div>
  </div>

  <div class = "row">
    <h2 class="my-5 fs-1" style="text-align: center;">The Louvre Collection</h2>
  </div>
  <div class = "row">
    <% @artworks.each do |artwork| %>
        <%= render "artworks/artwork", artwork: artwork %>
    <% end %>
  </div>
  <br>
  <br>
</div>

<div
  id="scroll-btn"
  class="d-flex justify-content-center"
  data-controller="backup"
  data-action="scroll@window->backup#controlBtn"
  style="position:fixed; left: 44%; bottom: 20px;">
    <div class="btn btn-primary" data-action="click->backup#scrollToTop" data-backup-target="scrollBtn">
      Back to the top
    </div>
</div>

app/views/artworks/show.html.erb
<%= render "shared/navbar" %>
<div class="container mt-4">
  <h2><%= @artwork.title %></h2>
  <h3 class="text-end"><%= @artwork.creator %></h3>
</div>

<div class="container card-artwork mt-4 mb-4">
  <% if @artwork.images.length > 1 %>
    <div id="artworkImages" class="carousel slide artwork-carousel" data-ride="carousel">
      <div class="carousel-indicators">
        <% @artwork.images.each_with_index do |image, i| %>
          <button type="button" data-bs-target="#artworkImages" data-bs-slide-to=<%= i %> class=<%= i.zero? ? "active" : "" %> aria-current="true" aria-label="Slide 1"></button>
        <% end %>
      </div>
      <div class="carousel-inner h-100">
        <div class="carousel-item active h-100">
          <img class="d-block w-100 artwork-carousel-item" src=<%= @artwork.images.first.url %> alt="First slide">
        </div>
        <% @artwork.images[1..].each do |image| %>
          <div class="carousel-item h-100">
            <img class="d-block w-100 artwork-carousel-item" src=<%= image.url %> alt=<%= "#{@artwork.title} Slide" %>>
          </div>
        <% end %>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#artworkImages" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#artworkImages" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  <% else %>
      <img  src=<%= @artwork.images.first.url %>>
  <% end %>
</div>

<div class="container mt-4">
  <div class="row p-4">
    <div class="col-6">
      <h4>Description</h4>
      <p><%= @artwork.description %></p>
      <p>Category: <%= @artwork.medium %></p>
      <p><strong>Dimensions: </strong> <%= @artwork.dimensions %><p>
      <p><strong>Creation date/period: </strong> <%= @artwork.creation_date.nil? ? "Unknown" : @artwork.creation_date %><p>
      <div class="reviews-card m-5 p-4">
        <h5 style="margin-bottom: 1.3em; color: #BBC1F3">Reviews from others clients</h4>
        <% if @reviews.empty? %>
            <h6>No review for this artwork</h6>
        <% else %>
          <% @reviews.each do |review| %>
            <h6>" <%= review[:content] %> " </h6>
            <div>
              <div class="text-primary" data-controller="star-display"
                  data-star-display-target="rating"
                  data-review-value=<%= review[:rating] %>></div>
                  <% user = User.find(review[:user_id]) %>
              <p><%= "#{user.first_name} #{user.last_name}" %> </p>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="col-6">
      <div class="card">
        <div class="p-5">
        <h3>New booking</h3>
          <div class="card-body" data-controller="checkout">
            <h5 class="card-title pb-5 text-end" data-checkout-target="pricePerDay">
              <%= @artwork.price_per_day.to_i %> $/day
            </h5>
            <%= simple_form_for [@artwork, @booking] do |f| %>
              <%= f.input :start_date, input_html: { data: {
                action: "change->checkout#updatePrice",
                checkout_target: "startDate",
              }
              } %>
              <%= f.input :end_date, input_html: { data: {
                action: "change->checkout#updatePrice",
                checkout_target: "endDate",
              }
              } %>
              <p class="text-end">Shipping cost included</p>
              <h5 class="text-end pb-4" data-checkout-target="totalPrice">Total price: <strong><%= @artwork.price_per_day.to_i %>$</strong></h5>
              <%= f.submit "Reserve", class: "btn btn-primary", style: "width: 100%;"%>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<%= render "shared/navbar" %>
<div class="container">
  <h1 class="text-center my-3">Hello <%= @user.first_name %>!</h1>
  <h2 class="text-center">Your Future Bookings</h2>
  <p class="text-center"><%= "You don't have any future bookings ..." if @user_future_bookings.empty? %></p>
  <div class="row">
    <% @user_future_bookings.each do |booking| %>
      <div class="card m-2 p-0 " style="width: 26rem; height: 48rem">
        <a href=<%= "/artworks/#{booking.artwork.id}" %>>
          <div class="card-artwork">
              <% image_url = booking.artwork.images.first.url %>
              <img src=<%= image_url %> class="card-img-top" alt="...">
          </div>
        </a>
        <div class="card-body">
          <span  data-controller="approval" data-action="scroll@window->approval#updateStatus" class="card-status">Pending</span>
          <span class="card-price">Total price: <%= booking.total_price.to_i %>$</span>
          <h5 class="card-title"><%= booking.artwork.title %></h5>
          <p class="card-text fst-italic"> <%= booking.artwork.creator %></p>
          <p class="card-text"><strong>Start date: </strong><%= booking.start_date %></p>
          <p class="card-text"><strong>End date: </strong><%= booking.end_date%></p>
          <%= link_to "Cancel", booking_path(booking), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"btn btn-primary cancel-btn"%>
        </div>
      </div>
    <% end %>
  </div>
  <h2 class="text-center mt-5 mb-3">Your Past Bookings</h2>
  <p class="text-center"><%= "You don't have any past bookings ..." if @user_past_bookings.empty? %></p>
  <div class="row">
    <% @user_past_bookings.each_with_index do |booking, index| %>
      <div class="card m-2 p-0" style="width: 26rem; height: 50rem">
        <a href=<%= "/artworks/#{booking.artwork.id}" %>>
          <div class="card-artwork">
              <% image_url = booking.artwork.images.first.url %>
              <img src=<%= image_url %> class="card-img-top" alt="...">
          </div>
        </a>
        <div class="card-body">
          <span class="card-price-past">Total price: <%= booking.total_price.to_i %>$</span>
          <h5 class="card-title"><%= booking.artwork.title %></h5>
          <p class="card-text fst-italic"> <%= booking.artwork.creator %></p>
          <p class="card-text"><strong>Start date: </strong><%= booking.start_date %></p>
          <p class="card-text"><strong>End date: </strong><%= booking.end_date%></p>
          <button class= 'btn btn-primary leavereview-btn' data-bs-toggle="modal" data-bs-target="#review-modal-<%= booking.artwork.id %>">Leave a review </button>
        </div>
      </div>
      <div class="modal fade" id="review-modal-<%= booking.artwork.id %>" tabindex="-1" aria-labelledby="review-modal" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title fs-5" id="reviewModalLabel">Leave a review</h4>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <%= simple_form_for [booking.artwork, @review] do |f| %>
              <%= f.input :content, label: "Comment"%>
              <%= f.input :rating, collection: (1..5).to_a, label: "Rate your experience", input_html: {data: {controller: "star-rating"}} %>            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-primary btn-modal" data-bs-dismiss="modal">Close</button>
              <%= f.button :submit, class:"btn btn-primary btn-modal" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <%# alert %>
  <% if !@user_future_bookings.empty? %>
  <div class="alert alert-warning alert-dismissible fade show opacity-0" role="alert" data-controller="approval" data-action="scroll@window->approval#notification">
  <strong>Great news!</strong> One of your booking has been approved
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentTheLouvre</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>


      <%= yield %>

    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render "shared/navbar" %>
<div class = "banner-container">
  <h1 class = "banner-h1">Rent the art you could never afford</h1>
    <%= link_to "Would you like La Joconde in your living room for a day or more?", artworks_path, class:"btn-banner" %>
</div>

<div class="container">
  <div class="row mb-5 mt-5">
    <div class="col-12 col-lg-4">
      <div class="card-container">
        <%= image_tag("statues-homepage.png", alt: "statues") %>
        <div class="card-infos pt-2 pb-3">
          <div class="p-2">
            <p>Find the masterpiece you want to rent in a large collection of arts</p>
          </div>
        </div>
      </div>
    </div>

    <div class="col-12 col-lg-4">
      <div class="card-container" style="height: 100%;">
        <%= image_tag("joconde-homepage.png", alt: "art") %>
        <div class="card-infos pt-3 pb-2">
          <div class="p-2">
            <p>In a few clicks, rent it for a day or more ...</p>
          </div>
        </div>
      </div>
    </div>

    <div class="col-12 col-lg-4">
      <div class="card-container" style="height: 100%;">
        <%= image_tag("room-homepage.png", alt: "room") %>
        <div class="card-infos pt-3 pb-2">
          <div class="p-2">
            <p>Exhibit it in your house, in the room of your choice</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/show.html.erb
<div class ="slider">
  <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="false">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="..." class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>First slide label</h5>
        <p>Some representative placeholder content for the first slide.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Second slide label</h5>
        <p>Some representative placeholder content for the second slide.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Third slide label</h5>
        <p>Some representative placeholder content for the third slide.</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

<div class = "card-reservation-container">
  <div class = "price"><%=random(1000..100 000)%>€/day</div>

  <div class = "btn button-primary">Connexion</div>

  <div class = "reservation-calcul-jour">
    <div class = "calcul-details">
    <%=%>
    </div>

    <div class = "result-price">
    <%=%>
    </div>
  </div>

  <div class = "deliver">
    <div> Frais de livraison </div>
    <div> 250€ H.T </div>
  </div>

  <div class = "reservation-total"> Total</div>

</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://www.louvre.fr/"><i class="fa-solid fa-l"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
  <%= link_to "Rent The Louvre", root_path, class:"navbar-title fs-3 text-white" %>
    <h5>This website is made with <i class="fas fa-heart"></i> by Cannelle, Nicolas & Marine.</h5>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "Rent The Louvre", root_path, class:"navbar-title ml-2" %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Menu</a>
             <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "All Artworks", artworks_path, class: "dropdown-item" %>
              <%= link_to "Your Dashboard", bookings_path, class: "dropdown-item", data: {turbo: false} %>
              <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbarhomepage.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "Rent The Louvre", root_path, class:"navbar-title ml-2" %>

  </div>
</div>